export const COLORS = {
  background: '#0a0e1a',
  surface: '#131929',
  surfaceAlt: '#1a2235',
  border: '#1e2d45',
  primary: '#00d4ff',
  primaryDark: '#0099bb',
  accent: '#ff6b35',
  success: '#22c55e',
  danger: '#ef4444',
  warning: '#f59e0b',
  textPrimary: '#ffffff',
  textSecondary: '#94a3b8',
  textMuted: '#475569',
  gold: '#fbbf24',
  silver: '#94a3b8',
};

export const POSITIONS = {
  DEF: { label: 'DEF', color: '#3b82f6', long: 'Defender' },
  MID: { label: 'MID', color: '#ec4899', long: 'Midfielder' },
  FWD: { label: 'FWD', color: '#f97316', long: 'Forward' },
  RUC: { label: 'RUC', color: '#22c55e', long: 'Ruck' },
};

// SuperCoach scoring formula weights
export const SC_WEIGHTS: Record<string, number> = {
  ek: 4,
  ik: 0,
  ck: -4,
  kla: 3,
  ehb: 1.5,
  ihb: 0,
  chb: -4,
  hbr: 1.5,
  hbg: 4.5,
  lbg: 4.5,
  goals: 8,
  behinds: 1,
  ga: 3.5,
  ba: 3.5,
  mu: 2,
  mc: 6,
  muo: 4,
  mco: 8,
  lm: 5,
  ko: 1.5,
  koc: 4,
  sm: 3,
  sp: 2,
  tackles: 4,
  freekicks_for: 4,
  freekicks_against: -4,
  hta: 5,
  gfh: 2,
  tihs: 5,
  buhs: 5,
  cbhs: 5,
};

export const SC_STAT_LABELS: Record<string, string> = {
  ek: 'Effective Kicks',
  ik: 'Ineffective Kicks',
  ck: 'Clanger Kicks',
  kla: 'Kick Long to Advantage',
  ehb: 'Effective Handballs',
  ihb: 'Ineffective Handballs',
  chb: 'Handball Clangers',
  hbr: 'Handball Receives',
  hbg: 'Hardball Gets',
  lbg: 'Loose Ball Gets',
  goals: 'Goals',
  behinds: 'Behinds',
  ga: 'Goal Assists',
  ba: 'Behind Assists',
  mu: 'Marks Uncontested (Maint.)',
  mc: 'Marks Contested (Maint.)',
  muo: 'Marks Uncontested (Opp.)',
  mco: 'Marks Contested (Opp.)',
  lm: 'Lead Marks',
  ko: 'Knock Ons',
  koc: 'Contested Knock Ons',
  sm: 'Smothers',
  sp: 'Spoils',
  tackles: 'Tackles',
  freekicks_for: 'Free Kicks For',
  freekicks_against: 'Free Kicks Against',
  hta: 'Hitouts to Advantage',
  gfh: 'Gather from Hitout',
  tihs: 'Throw-In Hitout Smash',
  buhs: 'Ball Up Hitout Smash',
  cbhs: 'Centre Bounce Hitout Smash',
};

export const CURRENT_YEAR = 2026;
export const CURRENT_ROUND = 3;
export const HISTORICAL_YEARS = [2025, 2024, 2023];
